version: "{build}"

#skip_tags: true

environment:
  matrix:
    - ARCH: x64
    - ARCH: x86

matrix:
  fast_finish: true

os:
  - Visual Studio 2015

build:
  verbosity: minimal

before_build:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /%ARCH% /release'

build_script:
  - cd src
  - sed -e "s/\$(LINKARGS2)/\$(LINKARGS2) | sed -e 's#.*\\\\r.*##'/" Make_mvc.mak > Make_mvc2.mak
  - if "%ARCH%" == "x64" (reg copy HKLM\SOFTWARE\Python\PythonCore\2.7 HKLM\SOFTWARE\Python\PythonCore\2.7-32 /s /reg:64) else (reg copy HKLM\SOFTWARE\Python\PythonCore\2.7 HKLM\SOFTWARE\Python\PythonCore\2.7-32 /s /reg:32)
  - if "%ARCH%" == "x64" (nmake -f Make_mvc2.mak CPU=AMD64 GUI=yes FEATURES=HUGE IME=yes MBYTE=yes ICONV=yes DEBUG=no PYTHON_VER=27 DYNAMIC_PYTHON=yes PYTHON=C:\Python27-x64 PYTHON3_VER=34 DYNAMIC_PYTHON3=yes PYTHON3=C:\Python34-x64 OLE=yes DIRECTX=yes && nmake -f Make_mvc2.mak GUI=no CPU=AMD64 GUI=yes FEATURES=HUGE IME=yes MBYTE=yes ICONV=yes DEBUG=no PYTHON_VER=27 DYNAMIC_PYTHON=yes PYTHON=C:\Python27-x64 PYTHON3_VER=34 DYNAMIC_PYTHON3=yes PYTHON3=C:\Python34-x64) else (nmake -f Make_mvc2.mak CPU=i386 GUI=yes FEATURES=HUGE IME=yes MBYTE=yes ICONV=yes DEBUG=no PYTHON_VER=27 DYNAMIC_PYTHON=yes PYTHON=C:\Python27 PYTHON3_VER=34 DYNAMIC_PYTHON3=yes PYTHON3=C:\Python34 PERL=C:\Perl DYNAMIC_PERL=yes OLE=yes DIRECTX=yes && nmake -f Make_mvc2.mak CPU=i386 GUI=no FEATURES=HUGE IME=yes MBYTE=yes ICONV=yes DEBUG=no PYTHON_VER=27 DYNAMIC_PYTHON=yes PYTHON=C:\Python27 PYTHON3_VER=34 DYNAMIC_PYTHON3=yes PYTHON3=C:\Python34)
  - .\gvim -silent -register
  - .\gvim -u NONE -c "redir @a | ver | 0put a | wq!" ver.txt
  - type ver.txt

after_build:
  - copy *.exe ..\runtime\
  - copy /Y xxd\*.exe ..\runtime
  - mkdir ..\runtime\GvimExt
  - copy /Y GvimExt\gvimext.dll ..\runtime\GvimExt\
  - copy /Y GvimExt\README.txt  ..\runtime\GvimExt\
  - copy /Y GvimExt\*.inf       ..\runtime\GvimExt\
  - copy /Y GvimExt\*.reg       ..\runtime\GvimExt\
  - 7z a ..\gvim_%ARCH%.zip ..\runtime\*

test_script:
  - cd testdir
  - nmake -f Make_dos.mak VIMPROG=..\gvim

artifacts:
  - path: gvim_x86.zip
    name: gVim_x86
  - path: gvim_x64.zip
    name: gVim_x64

deploy:
  - provider: GitHub
    release: vim-$(APPVEYOR_REPO_TAG_NAME)
    description: 'Nightly Vim Windows build snapshots'
    auth_token:
      secure: kH0D/3t+1Mc8OChKhe+voKlMO0aMwnlUr64QoZOJC6BaVwy+Us3ZHq9Oo+aBzjYc
    artifact: /gVim/
    draft: false
    prerelease: false
    on:
      appveyor-repo-tag: true
