version: "{build}"

#skip_tags: true

environment:
  matrix:
    - ARCH: x64
    - ARCH: x86

matrix:
  fast_finish: true

#os:
#  - Visual Studio 2015

build:
  verbosity: minimal

before_build:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /%ARCH% /release'
  - src\appveyor.bat install

build_script:
  - cd src
  - appveyor.bat build
  - .\gvim -u NONE -c "redir @a | ver | 0put a | wq!" ver.txt
  - type ver.txt
  - .\vim --version

after_build:
  - copy *.exe ..\runtime\
  - copy /Y xxd\*.exe ..\runtime
  - mkdir ..\runtime\GvimExt
  - copy /Y GvimExt\gvimext.dll ..\runtime\GvimExt\
  - copy /Y GvimExt\README.txt  ..\runtime\GvimExt\
  - copy /Y GvimExt\*.inf       ..\runtime\GvimExt\
  - copy /Y GvimExt\*.reg       ..\runtime\GvimExt\
  - 7z a ..\gvim_%ARCH%.zip ..\runtime\*

test_script:
  - cd testdir
  - nmake -f Make_dos.mak VIMPROG=..\gvim
  - nmake -f Make_dos.mak VIMPROG=..\vim

artifacts:
  - path: gvim_x86.zip
    name: gVim_x86
  - path: gvim_x64.zip
    name: gVim_x64

deploy:
  - provider: GitHub
    release: vim-$(APPVEYOR_REPO_TAG_NAME)
    description: 'Nightly Vim Windows build snapshots'
    auth_token:
      secure: ZfZRBCokF4rGIlyS0Nmgcn3g30vhz48ZKvIsF4ZGTv5HYVVPvldOtNQt3ZhtVUEl
    artifact: /gVim/
    draft: false
    prerelease: false
    on:
      appveyor-repo-tag: true
